//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IInteractive.WebTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IInteractive.WebTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;linkCheckerConfig&quot; type=&quot;IInteractive.WebConsole.LinkCheckerConfigSection, IInteractive.WebConsole&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;linkCheckerConfig name=&quot;Link Checker Tests&quot; description=&quot;Tests the links on the site.&quot; recursionLimit=&quot;3&quot; timeout=&quot;50&quot; maxRemoteAutomaticRedirects=&quot;10&quot;&gt;
        ///        &lt;seeds&gt;
        ///            &lt;clear /&gt;
        ///            &lt;add uri=&quot;{0}&quot;/&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CaseA {
            get {
                return ResourceManager.GetString("CaseA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;linkCheckerConfig&quot; type=&quot;IInteractive.WebConsole.LinkCheckerConfigSection, IInteractive.WebConsole&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;linkCheckerConfig name=&quot;Link Checker Tests&quot; description=&quot;Tests the links on the site.&quot; recursionLimit=&quot;3&quot; timeout=&quot;50&quot; maxRemoteAutomaticRedirects=&quot;10&quot;&gt;
        ///        &lt;seeds&gt;
        ///            &lt;clear /&gt;
        ///            &lt;add uri=&quot;{0}&quot;/&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CaseB {
            get {
                return ResourceManager.GetString("CaseB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;linkCheckerConfig&quot; type=&quot;IInteractive.WebConsole.LinkCheckerConfigSection, IInteractive.WebConsole&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;linkCheckerConfig name=&quot;Link Checker Tests&quot; description=&quot;Tests the links on the site.&quot; recursionLimit=&quot;3&quot; timeout=&quot;50&quot;&gt;
        ///        &lt;seeds&gt;
        ///            &lt;clear /&gt;
        ///            &lt;add uri=&quot;{0}&quot;/&gt;
        ///        &lt;/seeds&gt;
        ///        &lt;browsers&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CaseC {
            get {
                return ResourceManager.GetString("CaseC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;linkCheckerConfig&quot; type=&quot;IInteractive.WebConsole.LinkCheckerConfigSection, IInteractive.WebConsole&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;linkCheckerConfig name=&quot;Link Checker Tests&quot; description=&quot;Tests the links on the site.&quot; recursionLimit=&quot;3&quot; maxRemoteAutomaticRedirects=&quot;10&quot;&gt;
        ///        &lt;seeds&gt;
        ///            &lt;clear /&gt;
        ///            &lt;add uri=&quot;{0}&quot;/&gt;
        ///        &lt;/seeds&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CaseD {
            get {
                return ResourceManager.GetString("CaseD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;linkCheckerConfig&quot; type=&quot;IInteractive.WebConsole.LinkCheckerConfigSection, IInteractive.WebConsole&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;linkCheckerConfig name=&quot;Link Checker Tests&quot; description=&quot;Tests the links on the site.&quot; recursionLimit=&quot;3&quot; timeout=&quot;5&quot; maxRemoteAutomaticRedirects=&quot;10&quot;&gt;
        ///        &lt;seeds&gt;
        ///            &lt;clear /&gt;
        ///            &lt;add uri=&quot;{0}&quot;/&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CaseE {
            get {
                return ResourceManager.GetString("CaseE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;linkCheckerConfig&quot; type=&quot;IInteractive.WebConsole.LinkCheckerConfigSection, IInteractive.WebConsole&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;linkCheckerConfig name=&quot;Link Checker Tests&quot; description=&quot;Tests the links on the site.&quot; recursionLimit=&quot;10&quot;&gt;
        ///		&lt;forbidden&gt;
        ///			&lt;clear /&gt;
        ///			&lt;add host=&quot;{0}&quot; /&gt;
        ///		&lt;/forbidden&gt;
        ///        &lt;seeds&gt;
        ///            &lt;clear /&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForbiddenConfig {
            get {
                return ResourceManager.GetString("ForbiddenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;linkCheckerConfig&quot; type=&quot;IInteractive.WebConsole.LinkCheckerConfigSection, IInteractive.WebConsole&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;linkCheckerConfig name=&quot;Link Checker Tests&quot; description=&quot;Tests the links on the site.&quot; recursionLimit=&quot;10&quot;&gt;
        ///        &lt;seeds&gt;
        ///            &lt;clear /&gt;
        ///            &lt;add uri=&quot;{0}&quot;/&gt;
        ///        &lt;/seeds&gt;
        ///        &lt;browsers&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotForbiddenConfig {
            get {
                return ResourceManager.GetString("NotForbiddenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;confSec&quot; type=&quot;IInteractive.WebTest.ConfSec, IInteractive.WebTest&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;confSec prop=&quot;{0}&quot;&gt;
        ///        &lt;confColl&gt;
        ///            &lt;clear /&gt;
        ///            &lt;add name=&quot;{1}&quot; prop=&quot;{2}&quot;/&gt;
        ///        &lt;/confColl&gt;
        ///    &lt;/confSec&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        public static string TestA {
            get {
                return ResourceManager.GetString("TestA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;configSections&gt;
        ///        &lt;section name=&quot;confSec&quot; type=&quot;IInteractive.WebTest.ConfSec, IInteractive.WebTest&quot; allowDefinition=&quot;Everywhere&quot; allowLocation=&quot;true&quot; /&gt;
        ///    &lt;/configSections&gt;
        ///    &lt;confSec prop=&quot;{0}&quot;&gt;
        ///        &lt;confColl&gt;
        ///            &lt;clear /&gt;
        ///            &lt;add name=&quot;{1}&quot; prop=&quot;{2}&quot; callback=&quot;2&quot;/&gt;
        ///        &lt;/confColl&gt;
        ///    &lt;/confSec&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        public static string TestB {
            get {
                return ResourceManager.GetString("TestB", resourceCulture);
            }
        }
    }
}
